matrix:
  include:
    - language: elm
      node_js: node
      elm:
          - latest-0.19.1
      elm_test: 0.19.1
      elm_format: 0.8.2
      before_script:
          - cd client
      script:
          - elm make src/Main.elm

    - language: rust
      rust: nightly
      before_script:
        - cd nom-mail-parser
      script:
        - cargo test

    - language: rust
      rust: nightly
      before_script:
        - cd server
      script:
        - cargo build
