matrix:
  include:
    - language: elm
      before_script:
          - cd client
      script:
          - elm make src/Main.elm

    - language: rust
      rust: nightly
      before_script:
        - cd server
      script:
        - cargo build
