[package]
name = "chouette"
version = "0.1.0"
authors = ["Thomas Forgione <thomas@forgione.fr>"]
edition = "2018"

[dependencies]
warp = "0.1.9"

[build-dependencies]
git2 = "0.8.0"
reqwest = "0.9.5"
flate2 = { version = "1.0", features = ["rust_backend"], default-features = false }
tar = "0.4.20"
