[package]
name = "chouette"
version = "0.1.0"
authors = ["Thomas Forgione <thomas@forgione.fr>"]
edition = "2018"

[dependencies]
warp = "0.1.9"
serde = "1.0.0"
serde_derive = "1.0.0"
toml = "0.4"
diesel = { version = "1.0.0", features = ["postgres"] }
rand = "0.6.1"
bcrypt = "0.2.1"
log = "0.4.6"
stderrlog = "0.4.1"
clap = "2.32.0"

[build-dependencies]
git2 = "0.8.0"
reqwest = "0.9.5"
flate2 = { version = "1.0", features = ["rust_backend"], default-features = false }
tar = "0.4.20"
